from dotenv import load_dotenv
load_dotenv()
from werkzeug.security import generate_password_hash

from backend import app, db
from backend.models import User, Game, Pokemon

with app.app_context():
  db.drop_all()
  db.create_all()


  # create users
  demo = User(username = 'Demo', email = 'demo@user.com', password = generate_password_hash('passwprd', method='sha256'))
  # ian = User(username = 'Ian', email = 'ian@aa.io')
  # javier = User(username = 'Javier', email = 'javier@aa.io')
  # dean = User(username = 'Dean', email = 'dean@aa.io')
  # angela = User(username = 'Angela', email = 'angela@aa.io')
  # soonmi = User(username = 'Soon-Mi', email = 'soonmi@aa.io')
  # alissa = User(username = 'Alissa', email = 'alissa@aa.io')

  # add users
  db.session.add(demo)
  # db.session.add(ian)
  # db.session.add(javier)
  # db.session.add(dean)
  # db.session.add(angela)
  # db.session.add(soonmi)
  # db.session.add(alissa)


  # create games
  red = Game(name = 'Red')
  blue = Game(name = 'Blue')
  yellow = Game(name = 'Yellow')

  # add games
  db.session.add(red)
  db.session.add(blue)
  db.session.add(yellow)

  # create pokemon
  Bulbasaur = Pokemon(name = 'Bulbasaur', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 7, weight = 69, hp = 45, attack = 49, defense = 49, special_attack = 65, special_defense = 65, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png')
  Ivysaur = Pokemon(name = 'Ivysaur', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 10, weight = 130, hp = 60, attack = 62, defense = 63, special_attack = 80, special_defense = 80, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png')
  Venusaur = Pokemon(name = 'Venusaur', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 20, weight = 1000, hp = 80, attack = 82, defense = 83, special_attack = 100, special_defense = 100, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png')
  Charmander = Pokemon(name = 'Charmander', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 85, hp = 39, attack = 52, defense = 43, special_attack = 60, special_defense = 50, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png')
  Charmeleon = Pokemon(name = 'Charmeleon', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 11, weight = 190, hp = 58, attack = 64, defense = 58, special_attack = 80, special_defense = 65, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png')
  Charizard = Pokemon(name = 'Charizard', type_1 = 'Fire', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 17, weight = 905, hp = 78, attack = 84, defense = 78, special_attack = 109, special_defense = 85, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png')
  Squirtle = Pokemon(name = 'Squirtle', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 5, weight = 90, hp = 44, attack = 48, defense = 65, special_attack = 50, special_defense = 64, speed = 43, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png')
  Wartortle = Pokemon(name = 'Wartortle', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 225, hp = 59, attack = 63, defense = 80, special_attack = 65, special_defense = 80, speed = 58, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png')
  Blastoise = Pokemon(name = 'Blastoise', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 16, weight = 855, hp = 79, attack = 83, defense = 100, special_attack = 85, special_defense = 105, speed = 78, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png')
  Caterpie = Pokemon(name = 'Caterpie', type_1 = 'Bug', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 3, weight = 29, hp = 45, attack = 30, defense = 35, special_attack = 20, special_defense = 20, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png')
  Metapod = Pokemon(name = 'Metapod', type_1 = 'Bug', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 7, weight = 99, hp = 50, attack = 20, defense = 55, special_attack = 25, special_defense = 25, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png')
  Butterfree = Pokemon(name = 'Butterfree', type_1 = 'Bug', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 11, weight = 320, hp = 60, attack = 45, defense = 50, special_attack = 90, special_defense = 80, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png')
  Weedle = Pokemon(name = 'Weedle', type_1 = 'Bug', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 3, weight = 32, hp = 40, attack = 35, defense = 30, special_attack = 20, special_defense = 20, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png')
  Kakuna = Pokemon(name = 'Kakuna', type_1 = 'Bug', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 6, weight = 100, hp = 45, attack = 25, defense = 50, special_attack = 25, special_defense = 25, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png')
  Beedrill = Pokemon(name = 'Beedrill', type_1 = 'Bug', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 10, weight = 295, hp = 65, attack = 90, defense = 40, special_attack = 45, special_defense = 80, speed = 75, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png')
  Pidgey = Pokemon(name = 'Pidgey', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 3, weight = 18, hp = 40, attack = 45, defense = 40, special_attack = 35, special_defense = 35, speed = 56, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png')
  Pidgeotto = Pokemon(name = 'Pidgeotto', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 11, weight = 300, hp = 63, attack = 60, defense = 55, special_attack = 50, special_defense = 50, speed = 71, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png')
  Pidgeot = Pokemon(name = 'Pidgeot', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 15, weight = 395, hp = 83, attack = 80, defense = 75, special_attack = 70, special_defense = 70, speed = 101, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png')
  Rattata = Pokemon(name = 'Rattata', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 3, weight = 35, hp = 30, attack = 56, defense = 35, special_attack = 25, special_defense = 35, speed = 72, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png')
  Raticate = Pokemon(name = 'Raticate', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 7, weight = 185, hp = 55, attack = 81, defense = 60, special_attack = 50, special_defense = 70, speed = 97, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png')
  Spearow = Pokemon(name = 'Spearow', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 3, weight = 20, hp = 40, attack = 60, defense = 30, special_attack = 31, special_defense = 31, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png')
  Fearow = Pokemon(name = 'Fearow', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 12, weight = 380, hp = 65, attack = 90, defense = 65, special_attack = 61, special_defense = 61, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png')
  Ekans = Pokemon(name = 'Ekans', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 20, weight = 69, hp = 35, attack = 60, defense = 44, special_attack = 40, special_defense = 54, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png')
  Arbok = Pokemon(name = 'Arbok', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 35, weight = 650, hp = 60, attack = 95, defense = 69, special_attack = 65, special_defense = 79, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png')
  Pikachu = Pokemon(name = 'Pikachu', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 60, hp = 35, attack = 55, defense = 40, special_attack = 50, special_defense = 50, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png')
  Raichu = Pokemon(name = 'Raichu', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 300, hp = 60, attack = 90, defense = 55, special_attack = 90, special_defense = 80, speed = 110, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png')
  Sandshrew = Pokemon(name = 'Sandshrew', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 120, hp = 50, attack = 75, defense = 85, special_attack = 20, special_defense = 30, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png')
  Sandslash = Pokemon(name = 'Sandslash', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 295, hp = 75, attack = 100, defense = 110, special_attack = 45, special_defense = 55, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png')
  Nidoran_F = Pokemon(name = 'Nidoran', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 70, hp = 55, attack = 47, defense = 52, special_attack = 40, special_defense = 40, speed = 41, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png')
  Nidorina = Pokemon(name = 'Nidorina', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 200, hp = 70, attack = 62, defense = 67, special_attack = 55, special_defense = 55, speed = 56, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png')
  Nidoqueen = Pokemon(name = 'Nidoqueen', type_1 = 'Poison', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 13, weight = 600, hp = 90, attack = 92, defense = 87, special_attack = 75, special_defense = 85, speed = 76, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png')
  Nidoran_M = Pokemon(name = 'Nidoran', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 5, weight = 90, hp = 46, attack = 57, defense = 40, special_attack = 40, special_defense = 40, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png')
  Nidorino = Pokemon(name = 'Nidorino', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 9, weight = 195, hp = 61, attack = 72, defense = 57, special_attack = 55, special_defense = 55, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png')
  Nidoking = Pokemon(name = 'Nidoking', type_1 = 'Poison', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 14, weight = 620, hp = 81, attack = 102, defense = 77, special_attack = 85, special_defense = 75, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png')
  Clefairy = Pokemon(name = 'Clefairy', type_1 = 'Fairy', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 75, hp = 70, attack = 45, defense = 48, special_attack = 60, special_defense = 65, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png')
  Clefable = Pokemon(name = 'Clefable', type_1 = 'Fairy', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 13, weight = 400, hp = 95, attack = 70, defense = 73, special_attack = 95, special_defense = 90, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png')
  Vulpix = Pokemon(name = 'Vulpix', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 99, hp = 38, attack = 41, defense = 40, special_attack = 50, special_defense = 65, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png')
  Ninetales = Pokemon(name = 'Ninetales', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 11, weight = 199, hp = 73, attack = 76, defense = 75, special_attack = 81, special_defense = 100, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png')
  Jigglypuff = Pokemon(name = 'Jigglypuff', type_1 = 'Normal', type_2 = 'Fairy', is_legendary = False, is_mythical =  False, height = 5, weight = 55, hp = 115, attack = 45, defense = 20, special_attack = 45, special_defense = 25, speed = 20, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png')
  Wigglytuff = Pokemon(name = 'Wigglytuff', type_1 = 'Normal', type_2 = 'Fairy', is_legendary = False, is_mythical =  False, height = 10, weight = 120, hp = 140, attack = 70, defense = 45, special_attack = 85, special_defense = 50, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png')
  Zubat = Pokemon(name = 'Zubat', type_1 = 'Poison', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 8, weight = 75, hp = 40, attack = 45, defense = 35, special_attack = 30, special_defense = 40, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png')
  Golbat = Pokemon(name = 'Golbat', type_1 = 'Poison', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 16, weight = 550, hp = 75, attack = 80, defense = 70, special_attack = 65, special_defense = 75, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png')
  Oddish = Pokemon(name = 'Oddish', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 5, weight = 54, hp = 45, attack = 50, defense = 55, special_attack = 75, special_defense = 65, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png')
  Gloom = Pokemon(name = 'Gloom', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 8, weight = 86, hp = 60, attack = 65, defense = 70, special_attack = 85, special_defense = 75, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png')
  Vileplume = Pokemon(name = 'Vileplume', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 12, weight = 186, hp = 75, attack = 80, defense = 85, special_attack = 110, special_defense = 90, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png')
  Paras = Pokemon(name = 'Paras', type_1 = 'Bug', type_2 = 'Grass', is_legendary = False, is_mythical =  False, height = 3, weight = 54, hp = 35, attack = 70, defense = 55, special_attack = 45, special_defense = 55, speed = 25, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png')
  Parasect = Pokemon(name = 'Parasect', type_1 = 'Bug', type_2 = 'Grass', is_legendary = False, is_mythical =  False, height = 10, weight = 295, hp = 60, attack = 95, defense = 80, special_attack = 60, special_defense = 80, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png')
  Venonat = Pokemon(name = 'Venonat', type_1 = 'Bug', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 10, weight = 300, hp = 60, attack = 55, defense = 50, special_attack = 40, special_defense = 55, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png')
  Venomoth = Pokemon(name = 'Venomoth', type_1 = 'Bug', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 15, weight = 125, hp = 70, attack = 65, defense = 60, special_attack = 90, special_defense = 75, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png')
  Diglett = Pokemon(name = 'Diglett', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 2, weight = 8, hp = 10, attack = 55, defense = 25, special_attack = 35, special_defense = 45, speed = 95, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png')
  Dugtrio = Pokemon(name = 'Dugtrio', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 7, weight = 333, hp = 35, attack = 100, defense = 50, special_attack = 50, special_defense = 70, speed = 120, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png')
  Meowth = Pokemon(name = 'Meowth', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 42, hp = 40, attack = 45, defense = 35, special_attack = 40, special_defense = 40, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png')
  Persian = Pokemon(name = 'Persian', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 320, hp = 65, attack = 70, defense = 60, special_attack = 65, special_defense = 65, speed = 115, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png')
  Psyduck = Pokemon(name = 'Psyduck', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 196, hp = 50, attack = 52, defense = 48, special_attack = 65, special_defense = 50, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png')
  Golduck = Pokemon(name = 'Golduck', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 17, weight = 766, hp = 80, attack = 82, defense = 78, special_attack = 95, special_defense = 80, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png')
  Mankey = Pokemon(name = 'Mankey', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 5, weight = 280, hp = 40, attack = 80, defense = 35, special_attack = 35, special_defense = 45, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png')
  Primeape = Pokemon(name = 'Primeape', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 320, hp = 65, attack = 105, defense = 60, special_attack = 60, special_defense = 70, speed = 95, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png')
  Growlithe = Pokemon(name = 'Growlithe', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 7, weight = 190, hp = 55, attack = 70, defense = 45, special_attack = 70, special_defense = 50, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png')
  Arcanine = Pokemon(name = 'Arcanine', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 19, weight = 1550, hp = 90, attack = 110, defense = 80, special_attack = 100, special_defense = 80, speed = 95, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png')
  Poliwag = Pokemon(name = 'Poliwag', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 124, hp = 40, attack = 50, defense = 40, special_attack = 40, special_defense = 40, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png')
  Poliwhirl = Pokemon(name = 'Poliwhirl', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 200, hp = 65, attack = 65, defense = 65, special_attack = 50, special_defense = 50, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png')
  Poliwrath = Pokemon(name = 'Poliwrath', type_1 = 'Water', type_2 = 'Fighting', is_legendary = False, is_mythical =  False, height = 13, weight = 540, hp = 90, attack = 95, defense = 95, special_attack = 70, special_defense = 90, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png')
  Abra = Pokemon(name = 'Abra', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 9, weight = 195, hp = 25, attack = 20, defense = 15, special_attack = 105, special_defense = 55, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png')
  Kadabra = Pokemon(name = 'Kadabra', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 13, weight = 565, hp = 40, attack = 35, defense = 30, special_attack = 120, special_defense = 70, speed = 105, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png')
  Alakazam = Pokemon(name = 'Alakazam', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 15, weight = 480, hp = 55, attack = 50, defense = 45, special_attack = 135, special_defense = 95, speed = 120, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png')
  Machop = Pokemon(name = 'Machop', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 195, hp = 70, attack = 80, defense = 50, special_attack = 35, special_defense = 35, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png')
  Machoke = Pokemon(name = 'Machoke', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 15, weight = 705, hp = 80, attack = 100, defense = 70, special_attack = 50, special_defense = 60, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png')
  Machamp = Pokemon(name = 'Machamp', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 16, weight = 1300, hp = 90, attack = 130, defense = 80, special_attack = 65, special_defense = 85, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png')
  Bellsprout = Pokemon(name = 'Bellsprout', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 7, weight = 40, hp = 50, attack = 75, defense = 35, special_attack = 70, special_defense = 30, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png')
  Weepinbell = Pokemon(name = 'Weepinbell', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 10, weight = 64, hp = 65, attack = 90, defense = 50, special_attack = 85, special_defense = 45, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png')
  Victreebel = Pokemon(name = 'Victreebel', type_1 = 'Grass', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 17, weight = 155, hp = 80, attack = 105, defense = 65, special_attack = 100, special_defense = 70, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png')
  Tentacool = Pokemon(name = 'Tentacool', type_1 = 'Water', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 9, weight = 455, hp = 40, attack = 40, defense = 35, special_attack = 50, special_defense = 100, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png')
  Tentacruel = Pokemon(name = 'Tentacruel', type_1 = 'Water', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 16, weight = 550, hp = 80, attack = 70, defense = 65, special_attack = 80, special_defense = 120, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png')
  Geodude = Pokemon(name = 'Geodude', type_1 = 'Rock', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 4, weight = 200, hp = 40, attack = 80, defense = 100, special_attack = 30, special_defense = 30, speed = 20, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png')
  Graveler = Pokemon(name = 'Graveler', type_1 = 'Rock', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 10, weight = 1050, hp = 55, attack = 95, defense = 115, special_attack = 45, special_defense = 45, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png')
  Golem = Pokemon(name = 'Golem', type_1 = 'Rock', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 14, weight = 3000, hp = 80, attack = 120, defense = 130, special_attack = 55, special_defense = 65, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png')
  Ponyta = Pokemon(name = 'Ponyta', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 300, hp = 50, attack = 85, defense = 55, special_attack = 65, special_defense = 65, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png')
  Rapidash = Pokemon(name = 'Rapidash', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 17, weight = 950, hp = 65, attack = 100, defense = 70, special_attack = 80, special_defense = 80, speed = 105, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png')
  Slowpoke = Pokemon(name = 'Slowpoke', type_1 = 'Water', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 12, weight = 360, hp = 90, attack = 65, defense = 65, special_attack = 40, special_defense = 40, speed = 15, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png')
  Slowbro = Pokemon(name = 'Slowbro', type_1 = 'Water', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 16, weight = 785, hp = 95, attack = 75, defense = 110, special_attack = 100, special_defense = 80, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png')
  Magnemite = Pokemon(name = 'Magnemite', type_1 = 'Electric', type_2 = 'Steel', is_legendary = False, is_mythical =  False, height = 3, weight = 60, hp = 25, attack = 35, defense = 70, special_attack = 95, special_defense = 55, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png')
  Magneton = Pokemon(name = 'Magneton', type_1 = 'Electric', type_2 = 'Steel', is_legendary = False, is_mythical =  False, height = 10, weight = 600, hp = 50, attack = 60, defense = 95, special_attack = 120, special_defense = 70, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png')
  Farfetchd = Pokemon(name = 'Farfetchd', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 8, weight = 150, hp = 52, attack = 90, defense = 55, special_attack = 58, special_defense = 62, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png')
  Doduo = Pokemon(name = 'Doduo', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 14, weight = 392, hp = 35, attack = 85, defense = 45, special_attack = 35, special_defense = 35, speed = 75, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png')
  Dodrio = Pokemon(name = 'Dodrio', type_1 = 'Normal', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 18, weight = 852, hp = 60, attack = 110, defense = 70, special_attack = 60, special_defense = 60, speed = 110, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png')
  Seel = Pokemon(name = 'Seel', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 11, weight = 900, hp = 65, attack = 45, defense = 55, special_attack = 45, special_defense = 70, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png')
  Dewgong = Pokemon(name = 'Dewgong', type_1 = 'Water', type_2 = 'Ice', is_legendary = False, is_mythical =  False, height = 17, weight = 1200, hp = 90, attack = 70, defense = 80, special_attack = 70, special_defense = 95, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png')
  Grimer = Pokemon(name = 'Grimer', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 9, weight = 300, hp = 80, attack = 80, defense = 50, special_attack = 40, special_defense = 50, speed = 25, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png')
  Muk = Pokemon(name = 'Muk', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 12, weight = 300, hp = 105, attack = 105, defense = 75, special_attack = 65, special_defense = 100, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png')
  Shellder = Pokemon(name = 'Shellder', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 3, weight = 40, hp = 30, attack = 65, defense = 100, special_attack = 45, special_defense = 25, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png')
  Cloyster = Pokemon(name = 'Cloyster', type_1 = 'Water', type_2 = 'Ice', is_legendary = False, is_mythical =  False, height = 15, weight = 1325, hp = 50, attack = 95, defense = 180, special_attack = 85, special_defense = 45, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png')
  Gastly = Pokemon(name = 'Gastly', type_1 = 'Ghost', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 13, weight = 1, hp = 30, attack = 35, defense = 30, special_attack = 100, special_defense = 35, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png')
  Haunter = Pokemon(name = 'Haunter', type_1 = 'Ghost', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 16, weight = 1, hp = 45, attack = 50, defense = 45, special_attack = 115, special_defense = 55, speed = 95, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png')
  Gengar = Pokemon(name = 'Gengar', type_1 = 'Ghost', type_2 = 'Poison', is_legendary = False, is_mythical =  False, height = 15, weight = 405, hp = 60, attack = 65, defense = 60, special_attack = 130, special_defense = 75, speed = 110, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png')
  Onix = Pokemon(name = 'Onix', type_1 = 'Rock', type_2 = 'Ground', is_legendary = False, is_mythical =  False, height = 88, weight = 2100, hp = 35, attack = 45, defense = 160, special_attack = 30, special_defense = 45, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png')
  Drowzee = Pokemon(name = 'Drowzee', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 324, hp = 60, attack = 48, defense = 45, special_attack = 43, special_defense = 90, speed = 42, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png')
  Hypno = Pokemon(name = 'Hypno', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 16, weight = 756, hp = 85, attack = 73, defense = 70, special_attack = 73, special_defense = 115, speed = 67, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png')
  Krabby = Pokemon(name = 'Krabby', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 65, hp = 30, attack = 105, defense = 90, special_attack = 25, special_defense = 25, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png')
  Kingler = Pokemon(name = 'Kingler', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 13, weight = 600, hp = 55, attack = 130, defense = 115, special_attack = 50, special_defense = 50, speed = 75, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png')
  Voltorb = Pokemon(name = 'Voltorb', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 5, weight = 104, hp = 40, attack = 30, defense = 50, special_attack = 55, special_defense = 55, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png')
  Electrode = Pokemon(name = 'Electrode', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 12, weight = 666, hp = 60, attack = 50, defense = 70, special_attack = 80, special_defense = 80, speed = 150, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png')
  Exeggcute = Pokemon(name = 'Exeggcute', type_1 = 'Grass', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 4, weight = 25, hp = 60, attack = 40, defense = 80, special_attack = 60, special_defense = 45, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png')
  Exeggutor = Pokemon(name = 'Exeggutor', type_1 = 'Grass', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 20, weight = 1200, hp = 95, attack = 95, defense = 85, special_attack = 125, special_defense = 75, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png')
  Cubone = Pokemon(name = 'Cubone', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 65, hp = 50, attack = 50, defense = 95, special_attack = 40, special_defense = 50, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png')
  Marowak = Pokemon(name = 'Marowak', type_1 = 'Ground', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 450, hp = 60, attack = 80, defense = 110, special_attack = 50, special_defense = 80, speed = 45, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png')
  Hitmonlee = Pokemon(name = 'Hitmonlee', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 15, weight = 498, hp = 50, attack = 120, defense = 53, special_attack = 35, special_defense = 110, speed = 87, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png')
  Hitmonchan = Pokemon(name = 'Hitmonchan', type_1 = 'Fighting', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 14, weight = 502, hp = 50, attack = 105, defense = 79, special_attack = 35, special_defense = 110, speed = 76, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png')
  Lickitung = Pokemon(name = 'Lickitung', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 12, weight = 655, hp = 90, attack = 55, defense = 75, special_attack = 60, special_defense = 75, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png')
  Koffing = Pokemon(name = 'Koffing', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 10, hp = 40, attack = 65, defense = 95, special_attack = 60, special_defense = 45, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png')
  Weezing = Pokemon(name = 'Weezing', type_1 = 'Poison', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 12, weight = 95, hp = 65, attack = 90, defense = 120, special_attack = 85, special_defense = 70, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png')
  Rhyhorn = Pokemon(name = 'Rhyhorn', type_1 = 'Ground', type_2 = 'Rock', is_legendary = False, is_mythical =  False, height = 10, weight = 1150, hp = 80, attack = 85, defense = 95, special_attack = 30, special_defense = 30, speed = 25, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png')
  Rhydon = Pokemon(name = 'Rhydon', type_1 = 'Ground', type_2 = 'Rock', is_legendary = False, is_mythical =  False, height = 19, weight = 1200, hp = 105, attack = 130, defense = 120, special_attack = 45, special_defense = 45, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png')
  Chansey = Pokemon(name = 'Chansey', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 11, weight = 346, hp = 250, attack = 5, defense = 5, special_attack = 35, special_defense = 105, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png')
  Tangela = Pokemon(name = 'Tangela', type_1 = 'Grass', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 350, hp = 65, attack = 55, defense = 115, special_attack = 100, special_defense = 40, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png')
  Kangaskhan = Pokemon(name = 'Kangaskhan', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 22, weight = 800, hp = 105, attack = 95, defense = 80, special_attack = 40, special_defense = 80, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png')
  Horsea = Pokemon(name = 'Horsea', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 4, weight = 80, hp = 30, attack = 40, defense = 70, special_attack = 70, special_defense = 25, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png')
  Seadra = Pokemon(name = 'Seadra', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 12, weight = 250, hp = 55, attack = 65, defense = 95, special_attack = 95, special_defense = 45, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png')
  Goldeen = Pokemon(name = 'Goldeen', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 6, weight = 150, hp = 45, attack = 67, defense = 60, special_attack = 35, special_defense = 50, speed = 63, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png')
  Seaking = Pokemon(name = 'Seaking', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 13, weight = 390, hp = 80, attack = 92, defense = 65, special_attack = 65, special_defense = 80, speed = 68, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png')
  Staryu = Pokemon(name = 'Staryu', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 345, hp = 30, attack = 45, defense = 55, special_attack = 70, special_defense = 55, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png')
  Starmie = Pokemon(name = 'Starmie', type_1 = 'Water', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 11, weight = 800, hp = 60, attack = 75, defense = 85, special_attack = 100, special_defense = 85, speed = 115, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png')
  Mr_Mime = Pokemon(name = 'Mr-Mime', type_1 = 'Psychic', type_2 = 'Fairy', is_legendary = False, is_mythical =  False, height = 13, weight = 545, hp = 40, attack = 45, defense = 65, special_attack = 100, special_defense = 120, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png')
  Scyther = Pokemon(name = 'Scyther', type_1 = 'Bug', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 15, weight = 560, hp = 70, attack = 110, defense = 80, special_attack = 55, special_defense = 80, speed = 105, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png')
  Jynx = Pokemon(name = 'Jynx', type_1 = 'Ice', type_2 = 'Psychic', is_legendary = False, is_mythical =  False, height = 14, weight = 406, hp = 65, attack = 50, defense = 35, special_attack = 115, special_defense = 95, speed = 95, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png')
  Electabuzz = Pokemon(name = 'Electabuzz', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 11, weight = 300, hp = 65, attack = 83, defense = 57, special_attack = 95, special_defense = 85, speed = 105, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png')
  Magmar = Pokemon(name = 'Magmar', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 13, weight = 445, hp = 65, attack = 95, defense = 57, special_attack = 100, special_defense = 85, speed = 93, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png')
  Pinsir = Pokemon(name = 'Pinsir', type_1 = 'Bug', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 15, weight = 550, hp = 65, attack = 125, defense = 100, special_attack = 55, special_defense = 70, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png')
  Tauros = Pokemon(name = 'Tauros', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 14, weight = 884, hp = 75, attack = 100, defense = 95, special_attack = 40, special_defense = 70, speed = 110, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png')
  Magikarp = Pokemon(name = 'Magikarp', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 9, weight = 100, hp = 20, attack = 10, defense = 55, special_attack = 15, special_defense = 20, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png')
  Gyarados = Pokemon(name = 'Gyarados', type_1 = 'Water', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 65, weight = 2350, hp = 95, attack = 125, defense = 79, special_attack = 60, special_defense = 100, speed = 81, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png')
  Lapras = Pokemon(name = 'Lapras', type_1 = 'Water', type_2 = 'Ice', is_legendary = False, is_mythical =  False, height = 25, weight = 2200, hp = 130, attack = 85, defense = 80, special_attack = 85, special_defense = 95, speed = 60, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png')
  Ditto = Pokemon(name = 'Ditto', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 3, weight = 40, hp = 48, attack = 48, defense = 48, special_attack = 48, special_defense = 48, speed = 48, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png')
  Eevee = Pokemon(name = 'Eevee', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 3, weight = 65, hp = 55, attack = 55, defense = 50, special_attack = 45, special_defense = 65, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png')
  Vaporeon = Pokemon(name = 'Vaporeon', type_1 = 'Water', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 10, weight = 290, hp = 130, attack = 65, defense = 60, special_attack = 110, special_defense = 95, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png')
  Jolteon = Pokemon(name = 'Jolteon', type_1 = 'Electric', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 245, hp = 65, attack = 65, defense = 60, special_attack = 110, special_defense = 95, speed = 130, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png')
  Flareon = Pokemon(name = 'Flareon', type_1 = 'Fire', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 9, weight = 250, hp = 65, attack = 130, defense = 60, special_attack = 95, special_defense = 110, speed = 65, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png')
  Porygon = Pokemon(name = 'Porygon', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 8, weight = 365, hp = 65, attack = 60, defense = 70, special_attack = 85, special_defense = 75, speed = 40, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png')
  Omanyte = Pokemon(name = 'Omanyte', type_1 = 'Rock', type_2 = 'Water', is_legendary = False, is_mythical =  False, height = 4, weight = 75, hp = 35, attack = 40, defense = 100, special_attack = 90, special_defense = 55, speed = 35, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png')
  Omastar = Pokemon(name = 'Omastar', type_1 = 'Rock', type_2 = 'Water', is_legendary = False, is_mythical =  False, height = 10, weight = 350, hp = 70, attack = 60, defense = 125, special_attack = 115, special_defense = 70, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png')
  Kabuto = Pokemon(name = 'Kabuto', type_1 = 'Rock', type_2 = 'Water', is_legendary = False, is_mythical =  False, height = 5, weight = 115, hp = 30, attack = 80, defense = 90, special_attack = 55, special_defense = 45, speed = 55, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png')
  Kabutops = Pokemon(name = 'Kabutops', type_1 = 'Rock', type_2 = 'Water', is_legendary = False, is_mythical =  False, height = 13, weight = 405, hp = 60, attack = 115, defense = 105, special_attack = 65, special_defense = 70, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png')
  Aerodactyl = Pokemon(name = 'Aerodactyl', type_1 = 'Rock', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 18, weight = 590, hp = 80, attack = 105, defense = 65, special_attack = 60, special_defense = 75, speed = 130, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png')
  Snorlax = Pokemon(name = 'Snorlax', type_1 = 'Normal', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 21, weight = 4600, hp = 160, attack = 110, defense = 65, special_attack = 65, special_defense = 110, speed = 30, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png')
  Articuno = Pokemon(name = 'Articuno', type_1 = 'Ice', type_2 = 'Flying', is_legendary = True, is_mythical =  False, height = 17, weight = 554, hp = 90, attack = 85, defense = 100, special_attack = 95, special_defense = 125, speed = 85, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png')
  Zapdos = Pokemon(name = 'Zapdos', type_1 = 'Electric', type_2 = 'Flying', is_legendary = True, is_mythical =  False, height = 16, weight = 526, hp = 90, attack = 90, defense = 85, special_attack = 125, special_defense = 90, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png')
  Moltres = Pokemon(name = 'Moltres', type_1 = 'Fire', type_2 = 'Flying', is_legendary = True, is_mythical =  False, height = 20, weight = 600, hp = 90, attack = 100, defense = 90, special_attack = 125, special_defense = 85, speed = 90, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png')
  Dratini = Pokemon(name = 'Dratini', type_1 = 'Dragon', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 18, weight = 33, hp = 41, attack = 64, defense = 45, special_attack = 50, special_defense = 50, speed = 50, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png')
  Dragonair = Pokemon(name = 'Dragonair', type_1 = 'Dragon', type_2 = 'None', is_legendary = False, is_mythical =  False, height = 40, weight = 165, hp = 61, attack = 84, defense = 65, special_attack = 70, special_defense = 70, speed = 70, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png')
  Dragonite = Pokemon(name = 'Dragonite', type_1 = 'Dragon', type_2 = 'Flying', is_legendary = False, is_mythical =  False, height = 22, weight = 2100, hp = 91, attack = 134, defense = 95, special_attack = 100, special_defense = 100, speed = 80, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png')
  Mewtwo = Pokemon(name = 'Mewtwo', type_1 = 'Psychic', type_2 = 'None', is_legendary = True, is_mythical =  False, height = 20, weight = 1220, hp = 106, attack = 110, defense = 90, special_attack = 154, special_defense = 90, speed = 130, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png')
  Mew = Pokemon(name = 'Mew', type_1 = 'Psychic', type_2 = 'None', is_legendary = False, is_mythical =  True, height = 4, weight = 40, hp = 100, attack = 100, defense = 100, special_attack = 100, special_defense = 100, speed = 100, official_artwork = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png')


  # add pokemon
  db.session.add(Bulbasaur)
  db.session.add(Ivysaur)
  db.session.add(Venusaur)
  db.session.add(Charmander)
  db.session.add(Charmeleon)
  db.session.add(Charizard)
  db.session.add(Squirtle)
  db.session.add(Wartortle)
  db.session.add(Blastoise)
  db.session.add(Caterpie)
  db.session.add(Metapod)
  db.session.add(Butterfree)
  db.session.add(Weedle)
  db.session.add(Kakuna)
  db.session.add(Beedrill)
  db.session.add(Pidgey)
  db.session.add(Pidgeotto)
  db.session.add(Pidgeot)
  db.session.add(Rattata)
  db.session.add(Raticate)
  db.session.add(Spearow)
  db.session.add(Fearow)
  db.session.add(Ekans)
  db.session.add(Arbok)
  db.session.add(Pikachu)
  db.session.add(Raichu)
  db.session.add(Sandshrew)
  db.session.add(Sandslash)
  db.session.add(Nidoran_F)
  db.session.add(Nidorina)
  db.session.add(Nidoqueen)
  db.session.add(Nidoran_M)
  db.session.add(Nidorino)
  db.session.add(Nidoking)
  db.session.add(Clefairy)
  db.session.add(Clefable)
  db.session.add(Vulpix)
  db.session.add(Ninetales)
  db.session.add(Jigglypuff)
  db.session.add(Wigglytuff)
  db.session.add(Zubat)
  db.session.add(Golbat)
  db.session.add(Oddish)
  db.session.add(Gloom)
  db.session.add(Vileplume)
  db.session.add(Paras)
  db.session.add(Parasect)
  db.session.add(Venonat)
  db.session.add(Venomoth)
  db.session.add(Diglett)
  db.session.add(Dugtrio)
  db.session.add(Meowth)
  db.session.add(Persian)
  db.session.add(Psyduck)
  db.session.add(Golduck)
  db.session.add(Mankey)
  db.session.add(Primeape)
  db.session.add(Growlithe)
  db.session.add(Arcanine)
  db.session.add(Poliwag)
  db.session.add(Poliwhirl)
  db.session.add(Poliwrath)
  db.session.add(Abra)
  db.session.add(Kadabra)
  db.session.add(Alakazam)
  db.session.add(Machop)
  db.session.add(Machoke)
  db.session.add(Machamp)
  db.session.add(Bellsprout)
  db.session.add(Weepinbell)
  db.session.add(Victreebel)
  db.session.add(Tentacool)
  db.session.add(Tentacruel)
  db.session.add(Geodude)
  db.session.add(Graveler)
  db.session.add(Golem)
  db.session.add(Ponyta)
  db.session.add(Rapidash)
  db.session.add(Slowpoke)
  db.session.add(Slowbro)
  db.session.add(Magnemite)
  db.session.add(Magneton)
  db.session.add(Farfetchd)
  db.session.add(Doduo)
  db.session.add(Dodrio)
  db.session.add(Seel)
  db.session.add(Dewgong)
  db.session.add(Grimer)
  db.session.add(Muk)
  db.session.add(Shellder)
  db.session.add(Cloyster)
  db.session.add(Gastly)
  db.session.add(Haunter)
  db.session.add(Gengar)
  db.session.add(Onix)
  db.session.add(Drowzee)
  db.session.add(Hypno)
  db.session.add(Krabby)
  db.session.add(Kingler)
  db.session.add(Voltorb)
  db.session.add(Electrode)
  db.session.add(Exeggcute)
  db.session.add(Exeggutor)
  db.session.add(Cubone)
  db.session.add(Marowak)
  db.session.add(Hitmonlee)
  db.session.add(Hitmonchan)
  db.session.add(Lickitung)
  db.session.add(Koffing)
  db.session.add(Weezing)
  db.session.add(Rhyhorn)
  db.session.add(Rhydon)
  db.session.add(Chansey)
  db.session.add(Tangela)
  db.session.add(Kangaskhan)
  db.session.add(Horsea)
  db.session.add(Seadra)
  db.session.add(Goldeen)
  db.session.add(Seaking)
  db.session.add(Staryu)
  db.session.add(Starmie)
  db.session.add(Mr_Mime)
  db.session.add(Scyther)
  db.session.add(Jynx)
  db.session.add(Electabuzz)
  db.session.add(Magmar)
  db.session.add(Pinsir)
  db.session.add(Tauros)
  db.session.add(Magikarp)
  db.session.add(Gyarados)
  db.session.add(Lapras)
  db.session.add(Ditto)
  db.session.add(Eevee)
  db.session.add(Vaporeon)
  db.session.add(Jolteon)
  db.session.add(Flareon)
  db.session.add(Porygon)
  db.session.add(Omanyte)
  db.session.add(Omastar)
  db.session.add(Kabuto)
  db.session.add(Kabutops)
  db.session.add(Aerodactyl)
  db.session.add(Snorlax)
  db.session.add(Articuno)
  db.session.add(Zapdos)
  db.session.add(Moltres)
  db.session.add(Dratini)
  db.session.add(Dragonair)
  db.session.add(Dragonite)
  db.session.add(Mewtwo)
  db.session.add(Mew)


  # commit all
  db.session.commit()
